#:schema node_modules/wrangler/config-schema.json
name = "my-notes-extension"
main = "src/index.ts"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "my_notes_extension"
id = "29dbfb5ba5624bc19fc9e5ac9b7a6a25"


[vars]
# 密碼
AUTH_PASSWORD = "9ab5110#ff2"

# Development Environment Configuration
[env.development]
vars = { AUTH_PASSWORD = "9ab5110#ff2" }
